services:
  - type: web
    name: ramudu-sita-backend
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
